### PR TITLE
#895: add support for IntelliJ 2023.2

### LINKED ISSUE #895: Update to IDEA 2023.2

### PR DESCRIPTION
**Pull request by mateusz-bajorek**
fixes #895

### CODE REVIEW

**Review by essobedo — CHANGES_REQUESTED** [review]
Hi, thank you for your contribution. Just a couple of small remarks to address

**Comment by essobedo** [comment]
Please also amend your commit message to have `#895: add support for IntelliJ 2023.2` or `Ref #895: add support for IntelliJ 2023.2`?

**Review by davsclaus — APPROVED** [review]

**Comment by mateusz-bajorek** [comment]
Huh, looks like the build fails.
When using 
```gradle
plugins {
    id "org.jetbrains.intellij" version "1.15.0"
}
```
the intellij gradle plugin can't correctly read dependencies in tests.
```
Caused by: java.io.IOException: /home/runner/.gradle/caches/modules-2/files-2.1/org.apache.camel/camel-allcomponents/3.20.6/e6159dae4ec9953dab0216303141d3ad1468b13/camel-allcomponents-3.20.6.pom
	...
Caused by: java.util.zip.ZipException: Archive is not a ZIP archive
```

However, when the original (unchanged) plugin version is used
```gradle
plugins {
    id "org.jetbrains.intellij" version "1.13.1"
}
```
`Must be precomputed` exception is thrown on many tests and I've found this being reported in other plugins as well (e.g. https://github.com/microsoft/azure-tools-for-java/issues/7755)

**Comment by davsclaus** [comment]
yeah that plugin can often not be upgraded - not sure how much JetBrains know about this

**Comment by davsclaus** [comment]
I wonder if 2023.2 have removed some APIs used for testing

com.github.cameltooling.idea.util.IdeaUtilsSkipEndpointValidationTestIT > testShouldSkipActiveMQConnectionFactoryConstructor FAILED
    java.lang.NoClassDefFoundError at DaemonListeners.java:343
        Caused by: java.lang.ExceptionInInitializerError at TestLoggerFactory.java:403
Executing test testShouldSkipQpidJmsConnectionFactoryConstructor [com.github.cameltooling.idea.util.IdeaUtilsSkipEndpointValidationTestIT] with result: FAILURE

**Comment by mateusz-bajorek** [comment]
Running the single test with full stacktrace points towards the exception I've mentioned before:
```
$ .\gradlew.bat --no-daemon test --tests "com.github.cameltooling.idea.util.IdeaUtilsSkipEndpointValidationTestIT.testShouldSkipSetBrokerUrlMethod"
(...)
> Task :camel-idea-plugin:test
OpenJDK 64-Bit Server VM warning: Archived non-system classes are disabled because the java.system.class.loader property is specified (value = "com.intellij.util.lang.PathClassLoader"). To use archived non-system classes, this property must not be set
CompileCommand: exclude com/intellij/openapi/vfs/impl/FilePartNodeRoot.trieDescend bool exclude = true
Executing test testShouldSkipSetBrokerUrlMethod [com.github.cameltooling.idea.util.IdeaUtilsSkipEndpointValidationTestIT] with result: FAILURE

com.github.cameltooling.idea.util.IdeaUtilsSkipEndpointValidationTestIT > testShouldSkipSetBrokerUrlMethod FAILED
    com.intellij.testFramework.TestLoggerFactory$TestLoggerAssertionError: Must be precomputed
        at com.intellij.testFramework.TestLoggerFactory$TestLogger.error(TestLoggerFactory.java:403)
        at com.intellij.openapi.diagnostic.Logger.error(Logger.java:370)
        at com.intellij.ui.scale.JBUIScale.computeSystemFontData(JBUIScale.kt:96)
        at com.intellij.ui.scale.JBUIScale.access$computeSystemFontData(JBUIScale.kt:31)
        at com.intellij.ui.scale.JBUIScale$systemFontData$1.invoke(JBUIScale.kt:87)
        at com.intellij.ui.scale.JBUIScale$systemFontData$1.invoke(JBUIScale.kt:86)
        at com.intellij.util.concurrency.SynchronizedClearableLazy._get_value_$lambda$1$lambda$0(SynchronizedClearableLazy.kt:41)
        at java.base@17.0.8/java.util.concurrent.atomic.AtomicReference.updateAndGet(AtomicReference.java:210)
        at com.intellij.util.concurrency.SynchronizedClearableLazy.getValue(SynchronizedClearableLazy.kt:40)
        at com.intellij.ui.scale.JBUIScale.getSystemFontData(JBUIScale.kt:388)
        at com.intellij.ui.scale.JBUIScale.computeSystemScaleFactor(JBUIScale.kt:208)
        at com.intellij.ui.scale.JBUIScale$systemScaleFactor$1.invoke(JBUIScale.kt:67)
        at com.intellij.ui.scale.JBUIScale$systemScaleFactor$1.invoke(JBUIScale.kt:66)
        at com.intellij.util.concurrency.SynchronizedClearableLazy._get_value_$lambda$1$lambda$0(SynchronizedClearableLazy.kt:41)
        at java.base@17.0.8/java.util.concurrent.atomic.AtomicReference.updateAndGet(AtomicReference.java:210)
        at com.intellij.util.concurrency.SynchronizedClearableLazy.getValue(SynchronizedClearableLazy.kt:40)
        at com.intellij.ui.scale.JBUIScale$userScaleFactor$1.invoke(JBUIScale.kt:42)
        at com.intellij.ui.scale.JBUIScale$userScaleFactor$1.invoke(JBUIScale.kt:41)
        at com.intellij.util.concurrency.SynchronizedClearableLazy._get_value_$lambda$1$lambda$0(SynchronizedClearableLazy.kt:41)
        at java.base@17.0.8/java.util.concurrent.atomic.AtomicReference.updateAndGet(AtomicReference.java:210)
        at com.intellij.util.concurrency.SynchronizedClearableLazy.getValue(SynchronizedClearableLazy.kt:40)
        at com.intellij.ui.scale.JBUIScale.scale(JBUIScale.kt:337)
        at com.intellij.ui.scale.UserScaleContext.<init>(UserScaleContext.java:23)
        at com.intellij.ui.scale.UserScaleContext.create(UserScaleContext.java:57)
        at com.intellij.util.ui.JBScalableIcon.<init>(JBScalableIcon.java:30)
        at com.intellij.util.ui.JBCachingScalableIcon.<init>(JBCachingScalableIcon.java:19)
        at com.intellij.util.ui.EmptyIcon.<init>(EmptyIcon.java:74)
        at com.intellij.util.ui.EmptyIcon.lambda$create$1(EmptyIcon.java:108)
        at java.base@17.0.8/java.util.HashMap.computeIfAbsent(HashMap.java:1220)
        at com.intellij.util.ui.EmptyIcon.create(EmptyIcon.java:107)
        at com.intellij.util.ui.EmptyIcon.create(EmptyIcon.java:56)
        at com.intellij.util.ui.EmptyIcon.create(EmptyIcon.java:47)
        at com.intellij.util.ui.EmptyIcon.<clinit>(EmptyIcon.java:27)
        at com.intellij.codeHighlighting.HighlightDisplayLevel.<init>(HighlightDisplayLevel.java:89)
        at com.intellij.codeHighlighting.HighlightDisplayLevel.<init>(HighlightDisplayLevel.java:34)
        at com.intellij.codeHighlighting.HighlightDisplayLevel.<clinit>(HighlightDisplayLevel.java:47)
        at com.intellij.codeInsight.daemon.impl.SeverityRegistrar.<clinit>(SeverityRegistrar.java:68)
        at com.intellij.codeInsight.daemon.impl.DaemonListeners.<init>(DaemonListeners.java:343)
        at java.base@17.0.8/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base@17.0.8/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
        at java.base@17.0.8/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base@17.0.8/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
        at java.base@17.0.8/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
        at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:95)
        at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:1011)
        at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:47)
        at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:43)
        at com.intellij.serviceContainer.BaseComponentAdapter.doCreateInstance(BaseComponentAdapter.kt:158)
        at com.intellij.serviceContainer.BaseComponentAdapter.createInstance(BaseComponentAdapter.kt:137)
        at com.intellij.serviceContainer.BaseComponentAdapter.access$createInstance(BaseComponentAdapter.kt:21)
        at com.intellij.serviceContainer.BaseComponentAdapter$getInstanceAsync$2.invokeSuspend(BaseComponentAdapter.kt:185)
        at com.intellij.serviceContainer.BaseComponentAdapter$getInstanceAsync$2.invoke(BaseComponentAdapter.kt)
        at com.intellij.serviceContainer.BaseComponentAdapter$getInstanceAsync$2.invoke(BaseComponentAdapter.kt)
        at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:78)
        at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:167)
        at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
        at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceAsync(BaseComponentAdapter.kt:180)
        at com.intellij.serviceContainer.ComponentManagerImpl.preloadService$suspendImpl(ComponentManagerImpl.kt:1162)
        at com.intellij.serviceContainer.ComponentManagerImpl.preloadService(ComponentManagerImpl.kt)
        at com.intellij.serviceContainer.ComponentManagerImpl$preloadServices$1.invokeSuspend(ComponentManagerImpl.kt:1146)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)

        Caused by:
        java.lang.Throwable: Must be precomputed
            at com.intellij.openapi.diagnostic.Logger.error(Logger.java:370)
            ... 64 more
```

`at com.intellij.ui.scale.JBUIScale.computeSystemFontData(JBUIScale.kt:96)`

This line was added in IntelliJ 232.8453 build https://github.com/JetBrains/intellij-community/blob/232.8453/platform/util/ui/src/com/intellij/ui/scale/JBUIScale.kt#L96 and later changed in the default IntelliJ 232 branch https://github.com/JetBrains/intellij-community/blob/232/platform/util/ui/src/com/intellij/ui/scale/JBUIScale.kt#L96: https://github.com/JetBrains/intellij-community/commit/7992f1c80616e9decbd22134421cfdac27a5daea (the 232 release build is 232.8660). I wouldn't be surprised if we had to wait to get a patch release that fixes this.

**Comment by davsclaus** [comment]
Thanks @mateusz-bajorek for the analysis.

BTW would you like to keep helping this project in the future? And if so we can invite you in the maintainers team

**Comment by mateusz-bajorek** [comment]
Sure, I can, at least as long I'm also actively using Camel :)

**Comment by mateusz-bajorek** [comment]
Found this https://github.com/jonathanlermitage/intellij-extra-icons-plugin/commit/f2710e67bb8f51eed25415897eda6f1a5a594b71 which solves the issue in this plugin's case as well, PR updated.

**Comment by davsclaus** [comment]
Great all tests passes.

**Pull request merged**
