### PR TITLE
Minor improvements

### PR DESCRIPTION
**Pull request by javaduke**
- DataSonnet Language Injection;
- camel-debug detection in classpath.

### CODE REVIEW

**Comment by davsclaus** [comment]
There are checkstyle failures when you change the order of the imports.
These errors you only get when running the build with gradle.

Wonder if you could fix these CS errors

**Comment by javaduke** [comment]
Strange, I just ran checkstyle and see no errors...

**Comment by davsclaus** [comment]
Did you run from command line

```
./gradlew clean build
```

There is reports the checkstyle errors

PS: Yes there are test errors

**Comment by javaduke** [comment]
Yes, just did it again, no errors. I also ran `gradlew checkstyleMain`, no errors.

**Pull request merged**
